### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by samkleeman1** [karthikj89/scgenetics#1]
Hi, 

Congratulations on the preprint and many thanks for making this available. I am wondering how to implement this code with the data used in the paper. The datasets seem to be available at https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker, but these do not exactly seem to match with the datasets referencing in your jupyter notebooks.

Kind regards,

Sam Kleeman
PhD Student, Cold Spring Harbor Laboratory

**Comment by karthikj89** [comment]
Hi Sam - Thanks for the note. We will update the folder to include all the additional datasets that were analyzed as well.

**Comment by samkleeman1** [comment]
Hi, 

I was wondering if you had any updates regarding this. Are you able to clarify how the datasets listed in https://github.com/karthikj89/scgenetics/blob/master/src/1.generateCelltypePrograms.ipynb match with https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/annotations/.

**Comment by karthikj89** [comment]
Hi Sam - We have updated the annotations folder to now include data from additional tissues which were missing previously. Thanks for pointing this out. The key names in the scdatasets dictionary are the corresponding folder names in the annotations folder. We have include a brief description at the top of the notebook to clarify this. Thanks!

**Comment by zhanglab2008** [comment]
Thanks team! Can you show me a way to recursively download all the files from the directory? I tried wget -r -np but doesn't work. Appreciated!

**Comment by karthikj89** [comment]
You can copy files from the google bucket with the gsutil tool. Try: 
gsutil cp -r gs://broad-alkesgroup-public/LDSCORE/Jagadeesh_Dey_sclinker/scdata/ .

**Comment by bitcometz** [comment]
hi,
In your provided notebook: https://github.com/karthikj89/scgenetics/blob/master/src/1.generateCelltypePrograms.ipynb

there are three files :
```python
scdatasets = {
    'alzheimers_brain' : (datapath + 'z_disease/alzheimers/healthy.h5ad', 'Subject'),
    'idoamit_healthy' : (datapath + 'z_disease/covid/covid-healthy.h5ad', 'sample'),
    'msbrain': (datapath + 'z_disease/multiplesclerosis/healthy-processed-annotated.h5ad', 'sample'),
    }
```

I cannot find in the following urls:
https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/scdata/

Could you help with this problem?

Thanks !!!
