### ISSUE TITLE
sclinker data access denied

### ISSUE THREAD

**Issue by shhuang1** [karthikj89/scgenetics#12]
Hello,

Starting a few hours ago I have been getting an "Access denied" error at https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker. Can you help?

Thanks!

**Comment by kkdey** [comment]
@shhuang1 We are making some changes to our bucket set up to lower egress rates. We will be back up by the end of the week - there may be some modifications to access paths. Please bear with us, thanks for using sc-linker and sorry for this inconvenience.

**Comment by shhuang1** [comment]
Thanks for the quick response.  I will try again at the end of the week.  Thank you for sharing the code and data!

**Comment by kkdey** [comment]
@shhuang1 The webpage is back up now.

**Comment by shhuang1** [comment]
@kkdey I can see them now.  Thanks!
