### ISSUE TITLE
Please help with the datasets?

### ISSUE THREAD

**Issue by bitcometz** [karthikj89/scgenetics#3]
Hi,
Congratulations on the preprint and many thanks for making this available.

In your provided notebook: https://github.com/karthikj89/scgenetics/blob/master/src/1.generateCelltypePrograms.ipynb

there are three files :
```python
scdatasets = {
    'alzheimers_brain' : (datapath + 'z_disease/alzheimers/healthy.h5ad', 'Subject'),
    'idoamit_healthy' : (datapath + 'z_disease/covid/covid-healthy.h5ad', 'sample'),
    'msbrain': (datapath + 'z_disease/multiplesclerosis/healthy-processed-annotated.h5ad', 'sample'),
    }
```

I cannot find in the following urls:
https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/scdata/

Could you help with this problem?

Thanks !!!

**Comment by karthikj89** [comment]
The data you have mentioned is now uploaded: https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/scdata/disease/

For the alzheimers data you will have to download from here: https://www.radc.rush.edu/docs/omics.htm

Thanks!

**Comment by bitcometz** [comment]
Thanks !!!

**Comment by econnolly7** [comment]
Hi there,
The link for the datasets no longer work. Could you reshare the link?
Thanks so much!
