### ISSUE TITLE
how to calculate gene scores for healty tissues ？

### ISSUE THREAD

**Issue by bitcometz** [karthikj89/scgenetics#7]
helllo， there are no gene scores for healty tissue, which is shown in your supplementary tables:

<html  xmlns:o="urn:schemas-microsoft-com:office:office"  xmlns:x="urn:schemas-microsoft-com:office:excel"  xmlns="http://www.w3.org/TR/REC-html40">
<head>

</head>
<body>

celltypes | traits | Escore | pEscore
-- | -- | -- | --
Bcells (1.0%) (Healthy) | Inflammatory bowel disease | 5.919 | 1.82E-05
Bcells (0.4%) (Disease Progression) | Inflammatory bowel disease | 7.063 | 3.68E-05
Dendritic cells (1.1%) (Healthy) | Inflammatory bowel disease | 8.524 | 2.86E-07
Dendritic cells (0.3%) (Disease Progression) | Inflammatory bowel disease | 6.673 | 0.000162

</body>

</html>

I’m wondering whether the calculation method of healthy tissue is the same as that of diseased tissue, but the comparison is reversed.

Best

**Comment by karthikj89** [comment]
Hi,

The gene scores for cell types in healthy tissues are computed by comparing a cell type of interest versus all other cell types in the tissue. This does not require a disease tissue to be used for comparison.

All the gene scores for health tissues can be found here: https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/gene_scores/cell_type_programs/

Hope this clarifies!
